/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTemasekFacilitiesEndpointsFacilityListResponseFromDiscriminatorValue, type TemasekFacilitiesEndpointsFacilityListResponse } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /facility
 */
export interface FacilityRequestBuilder extends BaseRequestBuilder<FacilityRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TemasekFacilitiesEndpointsFacilityListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TemasekFacilitiesEndpointsFacilityListResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const FacilityRequestBuilderUriTemplate = "{+baseurl}/facility";
/**
 * Metadata for all the requests in the request builder.
 */
export const FacilityRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: FacilityRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createTemasekFacilitiesEndpointsFacilityListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
