/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FastEndpointsErrorResponse_Errors}
 */
// @ts-ignore
export function createFastEndpointsErrorResponse_ErrorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFastEndpointsErrorResponse_Errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FastEndpointsErrorResponse}
 */
// @ts-ignore
export function createFastEndpointsErrorResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFastEndpointsErrorResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TemasekFacilitiesEndpointsBookingByIdDeleteResponse}
 */
// @ts-ignore
export function createTemasekFacilitiesEndpointsBookingByIdDeleteResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTemasekFacilitiesEndpointsBookingByIdDeleteResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TemasekFacilitiesEndpointsBookingByIdGetResponse}
 */
// @ts-ignore
export function createTemasekFacilitiesEndpointsBookingByIdGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTemasekFacilitiesEndpointsBookingByIdGetResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TemasekFacilitiesEndpointsBookingByIdPostRequest}
 */
// @ts-ignore
export function createTemasekFacilitiesEndpointsBookingByIdPostRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTemasekFacilitiesEndpointsBookingByIdPostRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TemasekFacilitiesEndpointsBookingByIdPostResponse}
 */
// @ts-ignore
export function createTemasekFacilitiesEndpointsBookingByIdPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTemasekFacilitiesEndpointsBookingByIdPostResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TemasekFacilitiesEndpointsBookingGetResponse}
 */
// @ts-ignore
export function createTemasekFacilitiesEndpointsBookingGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTemasekFacilitiesEndpointsBookingGetResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TemasekFacilitiesEndpointsFacilityListFacilityItem}
 */
// @ts-ignore
export function createTemasekFacilitiesEndpointsFacilityListFacilityItemFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTemasekFacilitiesEndpointsFacilityListFacilityItem;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TemasekFacilitiesEndpointsFacilityListResponse}
 */
// @ts-ignore
export function createTemasekFacilitiesEndpointsFacilityListResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTemasekFacilitiesEndpointsFacilityListResponse;
}
/**
 * The deserialization information for the current model
 * @param FastEndpointsErrorResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFastEndpointsErrorResponse(fastEndpointsErrorResponse: Partial<FastEndpointsErrorResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Errors": n => { fastEndpointsErrorResponse.errors = n.getObjectValue<FastEndpointsErrorResponse_Errors>(createFastEndpointsErrorResponse_ErrorsFromDiscriminatorValue); },
        "Message": n => { fastEndpointsErrorResponse.messageEscaped = n.getStringValue() ?? "One or more errors occurred!"; },
        "StatusCode": n => { fastEndpointsErrorResponse.statusCode = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param FastEndpointsErrorResponse_Errors The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFastEndpointsErrorResponse_Errors(fastEndpointsErrorResponse_Errors: Partial<FastEndpointsErrorResponse_Errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param TemasekFacilitiesEndpointsBookingByIdDeleteResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTemasekFacilitiesEndpointsBookingByIdDeleteResponse(temasekFacilitiesEndpointsBookingByIdDeleteResponse: Partial<TemasekFacilitiesEndpointsBookingByIdDeleteResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Conduct": n => { temasekFacilitiesEndpointsBookingByIdDeleteResponse.conduct = n.getStringValue(); },
        "Description": n => { temasekFacilitiesEndpointsBookingByIdDeleteResponse.description = n.getStringValue(); },
        "EndDateTime": n => { temasekFacilitiesEndpointsBookingByIdDeleteResponse.endDateTime = n.getDateValue(); },
        "FacilityName": n => { temasekFacilitiesEndpointsBookingByIdDeleteResponse.facilityName = n.getStringValue(); },
        "Id": n => { temasekFacilitiesEndpointsBookingByIdDeleteResponse.id = n.getStringValue(); },
        "PocName": n => { temasekFacilitiesEndpointsBookingByIdDeleteResponse.pocName = n.getStringValue(); },
        "PocPhone": n => { temasekFacilitiesEndpointsBookingByIdDeleteResponse.pocPhone = n.getStringValue(); },
        "StartDateTime": n => { temasekFacilitiesEndpointsBookingByIdDeleteResponse.startDateTime = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param TemasekFacilitiesEndpointsBookingByIdGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTemasekFacilitiesEndpointsBookingByIdGetResponse(temasekFacilitiesEndpointsBookingByIdGetResponse: Partial<TemasekFacilitiesEndpointsBookingByIdGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Conduct": n => { temasekFacilitiesEndpointsBookingByIdGetResponse.conduct = n.getStringValue(); },
        "Description": n => { temasekFacilitiesEndpointsBookingByIdGetResponse.description = n.getStringValue(); },
        "EndDateTime": n => { temasekFacilitiesEndpointsBookingByIdGetResponse.endDateTime = n.getDateValue(); },
        "FacilityName": n => { temasekFacilitiesEndpointsBookingByIdGetResponse.facilityName = n.getStringValue(); },
        "Id": n => { temasekFacilitiesEndpointsBookingByIdGetResponse.id = n.getStringValue(); },
        "PocName": n => { temasekFacilitiesEndpointsBookingByIdGetResponse.pocName = n.getStringValue(); },
        "PocPhone": n => { temasekFacilitiesEndpointsBookingByIdGetResponse.pocPhone = n.getStringValue(); },
        "StartDateTime": n => { temasekFacilitiesEndpointsBookingByIdGetResponse.startDateTime = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param TemasekFacilitiesEndpointsBookingByIdPostRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTemasekFacilitiesEndpointsBookingByIdPostRequest(temasekFacilitiesEndpointsBookingByIdPostRequest: Partial<TemasekFacilitiesEndpointsBookingByIdPostRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Conduct": n => { temasekFacilitiesEndpointsBookingByIdPostRequest.conduct = n.getStringValue(); },
        "Description": n => { temasekFacilitiesEndpointsBookingByIdPostRequest.description = n.getStringValue(); },
        "PocName": n => { temasekFacilitiesEndpointsBookingByIdPostRequest.pocName = n.getStringValue(); },
        "PocPhone": n => { temasekFacilitiesEndpointsBookingByIdPostRequest.pocPhone = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param TemasekFacilitiesEndpointsBookingByIdPostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTemasekFacilitiesEndpointsBookingByIdPostResponse(temasekFacilitiesEndpointsBookingByIdPostResponse: Partial<TemasekFacilitiesEndpointsBookingByIdPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Conduct": n => { temasekFacilitiesEndpointsBookingByIdPostResponse.conduct = n.getStringValue(); },
        "Description": n => { temasekFacilitiesEndpointsBookingByIdPostResponse.description = n.getStringValue(); },
        "EndDateTime": n => { temasekFacilitiesEndpointsBookingByIdPostResponse.endDateTime = n.getDateValue(); },
        "FacilityName": n => { temasekFacilitiesEndpointsBookingByIdPostResponse.facilityName = n.getStringValue(); },
        "Id": n => { temasekFacilitiesEndpointsBookingByIdPostResponse.id = n.getStringValue(); },
        "PocName": n => { temasekFacilitiesEndpointsBookingByIdPostResponse.pocName = n.getStringValue(); },
        "PocPhone": n => { temasekFacilitiesEndpointsBookingByIdPostResponse.pocPhone = n.getStringValue(); },
        "StartDateTime": n => { temasekFacilitiesEndpointsBookingByIdPostResponse.startDateTime = n.getDateValue(); },
        "UserPhone": n => { temasekFacilitiesEndpointsBookingByIdPostResponse.userPhone = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param TemasekFacilitiesEndpointsBookingGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTemasekFacilitiesEndpointsBookingGetResponse(temasekFacilitiesEndpointsBookingGetResponse: Partial<TemasekFacilitiesEndpointsBookingGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Conduct": n => { temasekFacilitiesEndpointsBookingGetResponse.conduct = n.getStringValue(); },
        "Description": n => { temasekFacilitiesEndpointsBookingGetResponse.description = n.getStringValue(); },
        "EndDateTime": n => { temasekFacilitiesEndpointsBookingGetResponse.endDateTime = n.getDateValue(); },
        "FacilityName": n => { temasekFacilitiesEndpointsBookingGetResponse.facilityName = n.getStringValue(); },
        "Id": n => { temasekFacilitiesEndpointsBookingGetResponse.id = n.getStringValue(); },
        "PocName": n => { temasekFacilitiesEndpointsBookingGetResponse.pocName = n.getStringValue(); },
        "PocPhone": n => { temasekFacilitiesEndpointsBookingGetResponse.pocPhone = n.getStringValue(); },
        "StartDateTime": n => { temasekFacilitiesEndpointsBookingGetResponse.startDateTime = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param TemasekFacilitiesEndpointsFacilityListFacilityItem The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTemasekFacilitiesEndpointsFacilityListFacilityItem(temasekFacilitiesEndpointsFacilityListFacilityItem: Partial<TemasekFacilitiesEndpointsFacilityListFacilityItem> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Group": n => { temasekFacilitiesEndpointsFacilityListFacilityItem.group = n.getStringValue(); },
        "Id": n => { temasekFacilitiesEndpointsFacilityListFacilityItem.id = n.getStringValue(); },
        "Name": n => { temasekFacilitiesEndpointsFacilityListFacilityItem.name = n.getStringValue(); },
        "Scope": n => { temasekFacilitiesEndpointsFacilityListFacilityItem.scope = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @param TemasekFacilitiesEndpointsFacilityListResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTemasekFacilitiesEndpointsFacilityListResponse(temasekFacilitiesEndpointsFacilityListResponse: Partial<TemasekFacilitiesEndpointsFacilityListResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "Facilities": n => { temasekFacilitiesEndpointsFacilityListResponse.facilities = n.getCollectionOfObjectValues<TemasekFacilitiesEndpointsFacilityListFacilityItem>(createTemasekFacilitiesEndpointsFacilityListFacilityItemFromDiscriminatorValue); },
    }
}
/**
 * the dto used to send an error response to the client
 */
export interface FastEndpointsErrorResponse extends ApiError, Parsable {
    /**
     * the collection of errors for the current context
     */
    errors?: FastEndpointsErrorResponse_Errors | null;
    /**
     * the message for the error response
     */
    messageEscaped?: string | null;
    /**
     * the http status code sent to the client. default is 400.
     */
    statusCode?: number | null;
}
/**
 * the collection of errors for the current context
 */
export interface FastEndpointsErrorResponse_Errors extends AdditionalDataHolder, Parsable {
}
/**
 * Serializes information the current object
 * @param FastEndpointsErrorResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFastEndpointsErrorResponse(writer: SerializationWriter, fastEndpointsErrorResponse: Partial<FastEndpointsErrorResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!fastEndpointsErrorResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<FastEndpointsErrorResponse_Errors>("Errors", fastEndpointsErrorResponse.errors, serializeFastEndpointsErrorResponse_Errors);
    writer.writeStringValue("Message", fastEndpointsErrorResponse.messageEscaped ?? "One or more errors occurred!");
    writer.writeNumberValue("StatusCode", fastEndpointsErrorResponse.statusCode);
}
/**
 * Serializes information the current object
 * @param FastEndpointsErrorResponse_Errors The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFastEndpointsErrorResponse_Errors(writer: SerializationWriter, fastEndpointsErrorResponse_Errors: Partial<FastEndpointsErrorResponse_Errors> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!fastEndpointsErrorResponse_Errors || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(fastEndpointsErrorResponse_Errors.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TemasekFacilitiesEndpointsBookingByIdDeleteResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTemasekFacilitiesEndpointsBookingByIdDeleteResponse(writer: SerializationWriter, temasekFacilitiesEndpointsBookingByIdDeleteResponse: Partial<TemasekFacilitiesEndpointsBookingByIdDeleteResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!temasekFacilitiesEndpointsBookingByIdDeleteResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("Conduct", temasekFacilitiesEndpointsBookingByIdDeleteResponse.conduct);
    writer.writeStringValue("Description", temasekFacilitiesEndpointsBookingByIdDeleteResponse.description);
    writer.writeDateValue("EndDateTime", temasekFacilitiesEndpointsBookingByIdDeleteResponse.endDateTime);
    writer.writeStringValue("FacilityName", temasekFacilitiesEndpointsBookingByIdDeleteResponse.facilityName);
    writer.writeStringValue("Id", temasekFacilitiesEndpointsBookingByIdDeleteResponse.id);
    writer.writeStringValue("PocName", temasekFacilitiesEndpointsBookingByIdDeleteResponse.pocName);
    writer.writeStringValue("PocPhone", temasekFacilitiesEndpointsBookingByIdDeleteResponse.pocPhone);
    writer.writeDateValue("StartDateTime", temasekFacilitiesEndpointsBookingByIdDeleteResponse.startDateTime);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TemasekFacilitiesEndpointsBookingByIdGetResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTemasekFacilitiesEndpointsBookingByIdGetResponse(writer: SerializationWriter, temasekFacilitiesEndpointsBookingByIdGetResponse: Partial<TemasekFacilitiesEndpointsBookingByIdGetResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!temasekFacilitiesEndpointsBookingByIdGetResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("Conduct", temasekFacilitiesEndpointsBookingByIdGetResponse.conduct);
    writer.writeStringValue("Description", temasekFacilitiesEndpointsBookingByIdGetResponse.description);
    writer.writeDateValue("EndDateTime", temasekFacilitiesEndpointsBookingByIdGetResponse.endDateTime);
    writer.writeStringValue("FacilityName", temasekFacilitiesEndpointsBookingByIdGetResponse.facilityName);
    writer.writeStringValue("Id", temasekFacilitiesEndpointsBookingByIdGetResponse.id);
    writer.writeStringValue("PocName", temasekFacilitiesEndpointsBookingByIdGetResponse.pocName);
    writer.writeStringValue("PocPhone", temasekFacilitiesEndpointsBookingByIdGetResponse.pocPhone);
    writer.writeDateValue("StartDateTime", temasekFacilitiesEndpointsBookingByIdGetResponse.startDateTime);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TemasekFacilitiesEndpointsBookingByIdPostRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTemasekFacilitiesEndpointsBookingByIdPostRequest(writer: SerializationWriter, temasekFacilitiesEndpointsBookingByIdPostRequest: Partial<TemasekFacilitiesEndpointsBookingByIdPostRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!temasekFacilitiesEndpointsBookingByIdPostRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("Conduct", temasekFacilitiesEndpointsBookingByIdPostRequest.conduct);
    writer.writeStringValue("Description", temasekFacilitiesEndpointsBookingByIdPostRequest.description);
    writer.writeStringValue("PocName", temasekFacilitiesEndpointsBookingByIdPostRequest.pocName);
    writer.writeStringValue("PocPhone", temasekFacilitiesEndpointsBookingByIdPostRequest.pocPhone);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TemasekFacilitiesEndpointsBookingByIdPostResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTemasekFacilitiesEndpointsBookingByIdPostResponse(writer: SerializationWriter, temasekFacilitiesEndpointsBookingByIdPostResponse: Partial<TemasekFacilitiesEndpointsBookingByIdPostResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!temasekFacilitiesEndpointsBookingByIdPostResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("Conduct", temasekFacilitiesEndpointsBookingByIdPostResponse.conduct);
    writer.writeStringValue("Description", temasekFacilitiesEndpointsBookingByIdPostResponse.description);
    writer.writeDateValue("EndDateTime", temasekFacilitiesEndpointsBookingByIdPostResponse.endDateTime);
    writer.writeStringValue("FacilityName", temasekFacilitiesEndpointsBookingByIdPostResponse.facilityName);
    writer.writeStringValue("Id", temasekFacilitiesEndpointsBookingByIdPostResponse.id);
    writer.writeStringValue("PocName", temasekFacilitiesEndpointsBookingByIdPostResponse.pocName);
    writer.writeStringValue("PocPhone", temasekFacilitiesEndpointsBookingByIdPostResponse.pocPhone);
    writer.writeDateValue("StartDateTime", temasekFacilitiesEndpointsBookingByIdPostResponse.startDateTime);
    writer.writeStringValue("UserPhone", temasekFacilitiesEndpointsBookingByIdPostResponse.userPhone);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TemasekFacilitiesEndpointsBookingGetResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTemasekFacilitiesEndpointsBookingGetResponse(writer: SerializationWriter, temasekFacilitiesEndpointsBookingGetResponse: Partial<TemasekFacilitiesEndpointsBookingGetResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!temasekFacilitiesEndpointsBookingGetResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("Conduct", temasekFacilitiesEndpointsBookingGetResponse.conduct);
    writer.writeStringValue("Description", temasekFacilitiesEndpointsBookingGetResponse.description);
    writer.writeDateValue("EndDateTime", temasekFacilitiesEndpointsBookingGetResponse.endDateTime);
    writer.writeStringValue("FacilityName", temasekFacilitiesEndpointsBookingGetResponse.facilityName);
    writer.writeStringValue("Id", temasekFacilitiesEndpointsBookingGetResponse.id);
    writer.writeStringValue("PocName", temasekFacilitiesEndpointsBookingGetResponse.pocName);
    writer.writeStringValue("PocPhone", temasekFacilitiesEndpointsBookingGetResponse.pocPhone);
    writer.writeDateValue("StartDateTime", temasekFacilitiesEndpointsBookingGetResponse.startDateTime);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TemasekFacilitiesEndpointsFacilityListFacilityItem The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTemasekFacilitiesEndpointsFacilityListFacilityItem(writer: SerializationWriter, temasekFacilitiesEndpointsFacilityListFacilityItem: Partial<TemasekFacilitiesEndpointsFacilityListFacilityItem> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!temasekFacilitiesEndpointsFacilityListFacilityItem || isSerializingDerivedType) { return; }
    writer.writeStringValue("Group", temasekFacilitiesEndpointsFacilityListFacilityItem.group);
    writer.writeStringValue("Id", temasekFacilitiesEndpointsFacilityListFacilityItem.id);
    writer.writeStringValue("Name", temasekFacilitiesEndpointsFacilityListFacilityItem.name);
    writer.writeCollectionOfPrimitiveValues<string>("Scope", temasekFacilitiesEndpointsFacilityListFacilityItem.scope);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param TemasekFacilitiesEndpointsFacilityListResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTemasekFacilitiesEndpointsFacilityListResponse(writer: SerializationWriter, temasekFacilitiesEndpointsFacilityListResponse: Partial<TemasekFacilitiesEndpointsFacilityListResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!temasekFacilitiesEndpointsFacilityListResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<TemasekFacilitiesEndpointsFacilityListFacilityItem>("Facilities", temasekFacilitiesEndpointsFacilityListResponse.facilities, serializeTemasekFacilitiesEndpointsFacilityListFacilityItem);
}
export interface TemasekFacilitiesEndpointsBookingByIdDeleteResponse extends Parsable {
    /**
     * The Conduct property
     */
    conduct?: string | null;
    /**
     * The Description property
     */
    description?: string | null;
    /**
     * The EndDateTime property
     */
    endDateTime?: Date | null;
    /**
     * The FacilityName property
     */
    facilityName?: string | null;
    /**
     * The Id property
     */
    id?: string | null;
    /**
     * The PocName property
     */
    pocName?: string | null;
    /**
     * The PocPhone property
     */
    pocPhone?: string | null;
    /**
     * The StartDateTime property
     */
    startDateTime?: Date | null;
}
export interface TemasekFacilitiesEndpointsBookingByIdGetResponse extends Parsable {
    /**
     * The Conduct property
     */
    conduct?: string | null;
    /**
     * The Description property
     */
    description?: string | null;
    /**
     * The EndDateTime property
     */
    endDateTime?: Date | null;
    /**
     * The FacilityName property
     */
    facilityName?: string | null;
    /**
     * The Id property
     */
    id?: string | null;
    /**
     * The PocName property
     */
    pocName?: string | null;
    /**
     * The PocPhone property
     */
    pocPhone?: string | null;
    /**
     * The StartDateTime property
     */
    startDateTime?: Date | null;
}
export interface TemasekFacilitiesEndpointsBookingByIdPostRequest extends Parsable {
    /**
     * The Conduct property
     */
    conduct?: string | null;
    /**
     * The Description property
     */
    description?: string | null;
    /**
     * The PocName property
     */
    pocName?: string | null;
    /**
     * The PocPhone property
     */
    pocPhone?: string | null;
}
export interface TemasekFacilitiesEndpointsBookingByIdPostResponse extends Parsable {
    /**
     * The Conduct property
     */
    conduct?: string | null;
    /**
     * The Description property
     */
    description?: string | null;
    /**
     * The EndDateTime property
     */
    endDateTime?: Date | null;
    /**
     * The FacilityName property
     */
    facilityName?: string | null;
    /**
     * The Id property
     */
    id?: string | null;
    /**
     * The PocName property
     */
    pocName?: string | null;
    /**
     * The PocPhone property
     */
    pocPhone?: string | null;
    /**
     * The StartDateTime property
     */
    startDateTime?: Date | null;
    /**
     * The UserPhone property
     */
    userPhone?: string | null;
}
export interface TemasekFacilitiesEndpointsBookingGetResponse extends Parsable {
    /**
     * The Conduct property
     */
    conduct?: string | null;
    /**
     * The Description property
     */
    description?: string | null;
    /**
     * The EndDateTime property
     */
    endDateTime?: Date | null;
    /**
     * The FacilityName property
     */
    facilityName?: string | null;
    /**
     * The Id property
     */
    id?: string | null;
    /**
     * The PocName property
     */
    pocName?: string | null;
    /**
     * The PocPhone property
     */
    pocPhone?: string | null;
    /**
     * The StartDateTime property
     */
    startDateTime?: Date | null;
}
export interface TemasekFacilitiesEndpointsFacilityListFacilityItem extends Parsable {
    /**
     * The Group property
     */
    group?: string | null;
    /**
     * The Id property
     */
    id?: string | null;
    /**
     * The Name property
     */
    name?: string | null;
    /**
     * The Scope property
     */
    scope?: string[] | null;
}
export interface TemasekFacilitiesEndpointsFacilityListResponse extends Parsable {
    /**
     * The Facilities property
     */
    facilities?: TemasekFacilitiesEndpointsFacilityListFacilityItem[] | null;
}
/* tslint:enable */
/* eslint-enable */
