/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {TemasekOperatorrFeaturesDutyShiftListResponse}
 */
// @ts-ignore
export function createTemasekOperatorrFeaturesDutyShiftListResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoTemasekOperatorrFeaturesDutyShiftListResponse;
}
/**
 * The deserialization information for the current model
 * @param TemasekOperatorrFeaturesDutyShiftListResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoTemasekOperatorrFeaturesDutyShiftListResponse(temasekOperatorrFeaturesDutyShiftListResponse: Partial<TemasekOperatorrFeaturesDutyShiftListResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "cdooId": n => { temasekOperatorrFeaturesDutyShiftListResponse.cdooId = n.getStringValue(); },
        "cdooName": n => { temasekOperatorrFeaturesDutyShiftListResponse.cdooName = n.getStringValue(); },
        "cdosId": n => { temasekOperatorrFeaturesDutyShiftListResponse.cdosId = n.getStringValue(); },
        "cdosName": n => { temasekOperatorrFeaturesDutyShiftListResponse.cdosName = n.getStringValue(); },
        "dcId": n => { temasekOperatorrFeaturesDutyShiftListResponse.dcId = n.getStringValue(); },
        "dcName": n => { temasekOperatorrFeaturesDutyShiftListResponse.dcName = n.getStringValue(); },
    }
}
/**
 * Serializes information the current object
 * @param TemasekOperatorrFeaturesDutyShiftListResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeTemasekOperatorrFeaturesDutyShiftListResponse(writer: SerializationWriter, temasekOperatorrFeaturesDutyShiftListResponse: Partial<TemasekOperatorrFeaturesDutyShiftListResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!temasekOperatorrFeaturesDutyShiftListResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("cdooId", temasekOperatorrFeaturesDutyShiftListResponse.cdooId);
    writer.writeStringValue("cdooName", temasekOperatorrFeaturesDutyShiftListResponse.cdooName);
    writer.writeStringValue("cdosId", temasekOperatorrFeaturesDutyShiftListResponse.cdosId);
    writer.writeStringValue("cdosName", temasekOperatorrFeaturesDutyShiftListResponse.cdosName);
    writer.writeStringValue("dcId", temasekOperatorrFeaturesDutyShiftListResponse.dcId);
    writer.writeStringValue("dcName", temasekOperatorrFeaturesDutyShiftListResponse.dcName);
}
export interface TemasekOperatorrFeaturesDutyShiftListResponse extends Parsable {
    /**
     * The cdooId property
     */
    cdooId?: string | null;
    /**
     * The cdooName property
     */
    cdooName?: string | null;
    /**
     * The cdosId property
     */
    cdosId?: string | null;
    /**
     * The cdosName property
     */
    cdosName?: string | null;
    /**
     * The dcId property
     */
    dcId?: string | null;
    /**
     * The dcName property
     */
    dcName?: string | null;
}
/* tslint:enable */
/* eslint-enable */
