/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTemasekFacilitiesEndpointsBookingGetResponseFromDiscriminatorValue, type TemasekFacilitiesEndpointsBookingGetResponse } from '../models/index.js';
// @ts-ignore
import { BookingItemRequestBuilderRequestsMetadata, type BookingItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Booking
 */
export interface BookingRequestBuilder extends BaseRequestBuilder<BookingRequestBuilder> {
    /**
     * Gets an item from the TemasekFacilities.Booking.item collection
     * @param id Unique identifier of the item
     * @returns {BookingItemRequestBuilder}
     */
     byId(id: string) : BookingItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TemasekFacilitiesEndpointsBookingGetResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TemasekFacilitiesEndpointsBookingGetResponse[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BookingRequestBuilderUriTemplate = "{+baseurl}/Booking";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const BookingRequestBuilderNavigationMetadata: Record<Exclude<keyof BookingRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: BookingItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["Id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const BookingRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: BookingRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createTemasekFacilitiesEndpointsBookingGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
