/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTemasekOperatorrFeaturesDutyShiftListResponseFromDiscriminatorValue, type TemasekOperatorrFeaturesDutyShiftListResponse } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DutyShift
 */
export interface DutyShiftRequestBuilder extends BaseRequestBuilder<DutyShiftRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TemasekOperatorrFeaturesDutyShiftListResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TemasekOperatorrFeaturesDutyShiftListResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DutyShiftRequestBuilderUriTemplate = "{+baseurl}/DutyShift";
/**
 * Metadata for all the requests in the request builder.
 */
export const DutyShiftRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DutyShiftRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createTemasekOperatorrFeaturesDutyShiftListResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
