/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsErrorResponseFromDiscriminatorValue, createTemasekFacilitiesEndpointsBookingByIdDeleteResponseFromDiscriminatorValue, createTemasekFacilitiesEndpointsBookingByIdGetResponseFromDiscriminatorValue, createTemasekFacilitiesEndpointsBookingByIdPostResponseFromDiscriminatorValue, serializeTemasekFacilitiesEndpointsBookingByIdPostRequest, serializeTemasekFacilitiesEndpointsBookingByIdPostResponse, type FastEndpointsErrorResponse, type TemasekFacilitiesEndpointsBookingByIdDeleteResponse, type TemasekFacilitiesEndpointsBookingByIdGetResponse, type TemasekFacilitiesEndpointsBookingByIdPostRequest, type TemasekFacilitiesEndpointsBookingByIdPostResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Booking/{Id}
 */
export interface BookingItemRequestBuilder extends BaseRequestBuilder<BookingItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TemasekFacilitiesEndpointsBookingByIdDeleteResponse>}
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TemasekFacilitiesEndpointsBookingByIdDeleteResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TemasekFacilitiesEndpointsBookingByIdGetResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TemasekFacilitiesEndpointsBookingByIdGetResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TemasekFacilitiesEndpointsBookingByIdPostResponse>}
     * @throws {FastEndpointsErrorResponse} error when the service returns a 400 status code
     */
     post(body: TemasekFacilitiesEndpointsBookingByIdPostRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TemasekFacilitiesEndpointsBookingByIdPostResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: TemasekFacilitiesEndpointsBookingByIdPostRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BookingItemRequestBuilderUriTemplate = "{+baseurl}/Booking/{Id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const BookingItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: BookingItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createTemasekFacilitiesEndpointsBookingByIdDeleteResponseFromDiscriminatorValue,
    },
    get: {
        uriTemplate: BookingItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createTemasekFacilitiesEndpointsBookingByIdGetResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: BookingItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFastEndpointsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createTemasekFacilitiesEndpointsBookingByIdPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeTemasekFacilitiesEndpointsBookingByIdPostRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
